/-
Copyright (c) 2026 Quang Dao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
import VCVio.CryptoFoundations.FiatShamir.Sigma.Stateful.Bridge
import VCVio.StateSeparating.IdenticalUntilBad
import Mathlib.Data.Real.ENatENNReal

/-!
# Native stateful Fiat-Shamir CMA game hops

This file is the replacement path for the old Fiat-Shamir HeapSSP H3 proof.
The theorems here are stated directly over `QueryImpl.Stateful` handlers and
the concrete `CmaState` product state.
-/

universe u

open ENNReal OracleSpec OracleComp ProbComp
open OracleComp.ProgramLogic.Relational

namespace FiatShamir.Stateful

variable (M : Type) [DecidableEq M]
variable (Commit : Type) [DecidableEq Commit]
variable (Chal : Type) [SampleableType Chal]
variable {Stmt Wit : Type} {rel : Stmt → Wit → Bool}
variable {Resp PrvState : Type}

/-! ## H3 state invariants and per-query loss -/

/-- Initial direct CMA data, without the trailing bad flag. -/
@[reducible] def cmaDataInit (M Commit Chal Stmt Wit : Type) :
    CmaData M Commit Chal Stmt Wit :=
  ([], ∅, none)

omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
/-- The direct CMA initial state is the initial data with bad unset. -/
@[simp]
lemma cmaInit_eq_cmaDataInit :
    cmaInit M Commit Chal Stmt Wit = (cmaDataInit M Commit Chal Stmt Wit, false) := rfl

/-- Number of live random-oracle cache entries in a direct stateful CMA cache. -/
noncomputable def roCacheCount (cache : RoCache M Commit Chal) : ℝ≥0∞ :=
  (cache.toSet.encard : ℝ≥0∞)

/-- Reachability invariant for the direct CMA data.

Cached keypairs, when present, must satisfy the relation generated by `hr.gen`.
The invariant is intentionally phrased on `CmaData`, not heap cells. -/
def CmaData.Valid
    {M : Type} {Commit : Type} {Chal Stmt Wit : Type}
    {rel : Stmt → Wit → Bool}
    (s : CmaData M Commit Chal Stmt Wit) : Prop :=
  match s.2.2 with
  | none => True
  | some (pk, sk) => rel pk sk = true

instance
    {M : Type} {Commit : Type} {Chal Stmt Wit : Type}
    {rel : Stmt → Wit → Bool}
    (s : CmaData M Commit Chal Stmt Wit) :
    Decidable (CmaData.Valid (rel := rel) s) := by
  unfold CmaData.Valid
  cases s.2.2 with
  | none => infer_instance
  | some ps =>
      cases ps
      infer_instance

omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
/-- The initial direct CMA data has no cached keypair, hence satisfies the
valid-keypair invariant. -/
lemma cmaDataInit_valid :
    CmaData.Valid (rel := rel) (cmaDataInit M Commit Chal Stmt Wit) := by
  simp [CmaData.Valid]

/-- Tight state-dependent per-signing-query loss for H3 on reachable states. -/
noncomputable def cmaSignEpsCore
    (ζ_zk β : ℝ≥0∞) (s : CmaData M Commit Chal Stmt Wit) : ℝ≥0∞ :=
  ζ_zk + roCacheCount M Commit Chal s.2.1 * β

/-- State-dependent per-signing-query loss for H3.

On reachable states this is `ζ_zk + roCacheCount · β`. Invalid keypair states
receive the conservative fallback cost `1`, which is useful for ungated
pointwise TV obligations. -/
noncomputable def cmaSignEps
    (ζ_zk β : ℝ≥0∞) (s : CmaData M Commit Chal Stmt Wit) : ℝ≥0∞ :=
  if CmaData.Valid (rel := rel) s then
    cmaSignEpsCore M Commit Chal ζ_zk β s
  else
    1

/-! ## H3 proof obligations -/

/-- Signing queries are the charged queries in the H3 hop. -/
abbrev cmaH3Costly :
    (cmaSpec M Commit Chal Resp Stmt).Domain → Prop :=
  IsCostlyQuery (M := M) (Commit := Commit) (Chal := Chal)
    (Resp := Resp) (Stmt := Stmt)

/-- Boolean distinguishing advantage for the native H3 pair from the direct
CMA initial state. -/
noncomputable abbrev cmaH3Advantage
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool) : ℝ :=
  (cmaReal M Commit Chal σ hr).advantage
    (cmaInit M Commit Chal Stmt Wit)
    (cmaSim M Commit Chal hr simT)
    (cmaInit M Commit Chal Stmt Wit) A

/-- Expected accumulated H3 signing loss in the real game. -/
noncomputable abbrev cmaH3ExpectedLoss
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) : ℝ≥0∞ :=
  expectedQuerySlack (cmaReal M Commit Chal σ hr)
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt))
    (cmaSignEpsCore M Commit Chal ζ_zk β) A qS
    (cmaInit M Commit Chal Stmt Wit)

/-- Per-query facts for the native H3 hop. -/
structure CmaH3StepFacts
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞) : Prop where
  /-- The real game preserves keypair validity while bad is false. -/
  preservesValid :
    (cmaReal M Commit Chal σ hr).PreservesNoBadInvariant
      (CmaData.Valid (rel := rel))
  /-- Signing queries are close by the state-dependent H3 loss. -/
  stepTvCostly :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
      cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt) t →
      ∀ (s : CmaData M Commit Chal Stmt Wit),
        CmaData.Valid (rel := rel) s →
          ENNReal.ofReal (tvDist
            (((cmaReal M Commit Chal σ hr) t).run (s, false))
            (((cmaSim M Commit Chal hr simT) t).run (s, false)))
            ≤ cmaSignEpsCore M Commit Chal ζ_zk β s
  /-- Non-signing queries agree pointwise. -/
  stepEqFree :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
      ¬ cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t →
      ∀ (p : CmaState M Commit Chal Stmt Wit),
        ((cmaReal M Commit Chal σ hr) t).run p =
          ((cmaSim M Commit Chal hr simT) t).run p
  /-- Once the real bad flag is true, it stays true. -/
  badMono :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
      (p : CmaState M Commit Chal Stmt Wit), p.2 = true →
        ∀ z ∈ support (((cmaReal M Commit Chal σ hr) t).run p), z.2.2 = true

/-- Computation-specific facts for applying the native H3 hop. -/
structure CmaH3RunFacts
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞) : Prop where
  /-- The adversary issues at most `qS` signing queries. -/
  queryBound : OracleComp.IsQueryBoundP A
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt)) qS
  /-- The real game never reaches bad from the initial state. -/
  badZero :
    Pr[ fun z : Bool × CmaState M Commit Chal Stmt Wit => z.2.2 = true |
      (simulateQ (cmaReal M Commit Chal σ hr) A).run
        (cmaInit M Commit Chal Stmt Wit)] = 0
  /-- The expected accumulated signing loss is at most the requested bound. -/
  expectedLossLe :
    cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤ εBound

/-! ## Real-game bad flag facts -/

/-- Stepwise preservation of a trailing Boolean flag lifts through
`simulateQ`. -/
theorem simulateQ_bad_preserved_of_step
    {ι ι' : Type} {spec : OracleSpec ι} {spec' : OracleSpec ι'}
    {σ : Type} {α : Type}
    (impl : QueryImpl spec (StateT (σ × Bool) (OracleComp spec')))
    (hstep : ∀ (t : spec.Domain) (p : σ × Bool) (z),
      z ∈ support ((impl t).run p) → z.2.2 = p.2)
    (oa : OracleComp spec α) (p : σ × Bool) {z : α × σ × Bool}
    (hz : z ∈ support ((simulateQ impl oa).run p)) :
    z.2.2 = p.2 := by
  induction oa using OracleComp.inductionOn generalizing p z with
  | pure x =>
      simp only [simulateQ_pure, StateT.run_pure, support_pure, Set.mem_singleton_iff] at hz
      subst z
      rfl
  | query_bind t k ih =>
      simp only [simulateQ_bind, simulateQ_query, OracleQuery.cont_query,
        OracleQuery.input_query, id_map, StateT.run_bind, support_bind,
        Set.mem_iUnion, exists_prop] at hz
      obtain ⟨up, hup, hz⟩ := hz
      exact (ih up.1 up.2 hz).trans (hstep t p up hup)

/-- One step of the real CMA game preserves the bad flag exactly. -/
theorem cmaReal_bad_preserved
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    z.2.2 = p.2 := by
  rcases p with ⟨⟨log, cache, keypair⟩, bad⟩
  rcases t with n | mc | m | ⟨⟩
  · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
      support_pure, Set.mem_singleton_iff, exists_prop] at hz
    obtain ⟨rc, _, rfl⟩ := hz
    rfl
  · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
      support_pure, Set.mem_singleton_iff, exists_prop] at hz
    obtain ⟨rc, _, rfl⟩ := hz
    rfl
  · rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
        support_pure, Set.mem_singleton_iff, exists_prop] at hz
      obtain ⟨pk_sk, _, sc, hsc, hrest⟩ := hz
      subst sc
      obtain ⟨i, _, rfl⟩ := hrest
      rfl
    · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
        support_pure, Set.mem_singleton_iff, exists_prop] at hz
      obtain ⟨sc, hsc, hrest⟩ := hz
      subst sc
      obtain ⟨i, _, rfl⟩ := hrest
      rfl
  · simp only [cmaReal, StateT.run_mk] at hz
    rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
        exists_prop] at hz
      obtain ⟨pk_sk, _, rfl⟩ := hz
      rfl
    · simp only [support_pure, Set.mem_singleton_iff] at hz
      subst z
      rfl

/-- Once the real CMA bad flag is true, one real step keeps it true. -/
theorem cmaReal_bad_mono
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
      (p : CmaState M Commit Chal Stmt Wit), p.2 = true →
        ∀ z ∈ support (((cmaReal M Commit Chal σ hr) t).run p), z.2.2 = true := by
  intro t p hp z hz
  exact (cmaReal_bad_preserved M Commit Chal σ hr t p z hz).trans hp

/-- The real CMA game never reaches bad from the initial state. -/
theorem cmaReal_probEvent_bad_eq_zero
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α) :
    Pr[ fun z : α × CmaState M Commit Chal Stmt Wit => z.2.2 = true |
      (simulateQ (cmaReal M Commit Chal σ hr) A).run
        (cmaInit M Commit Chal Stmt Wit)] = 0 := by
  rw [probEvent_eq_zero_iff]
  intro z hz hbad
  have hpres := simulateQ_bad_preserved_of_step
    (impl := cmaReal M Commit Chal σ hr)
    (fun t p z hz => cmaReal_bad_preserved M Commit Chal σ hr t p z hz)
    A (cmaInit M Commit Chal Stmt Wit) hz
  change z.2.2 = false at hpres
  rw [hpres] at hbad
  contradiction

/-- One real CMA step preserves keypair validity. -/
theorem cmaReal_valid_preserved
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (hpvalid : CmaData.Valid (rel := rel) p.1)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    CmaData.Valid (rel := rel) z.2.1 := by
  rcases p with ⟨⟨log, cache, keypair⟩, bad⟩
  rcases t with n | mc | m | ⟨⟩
  · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
      support_pure, Set.mem_singleton_iff, exists_prop] at hz
    obtain ⟨rc, _, rfl⟩ := hz
    simpa [CmaData.Valid] using hpvalid
  · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
      support_pure, Set.mem_singleton_iff, exists_prop] at hz
    obtain ⟨rc, _, rfl⟩ := hz
    simpa [CmaData.Valid] using hpvalid
  · rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
        support_pure, Set.mem_singleton_iff, exists_prop] at hz
      obtain ⟨pk_sk, hgen, sc, hsc, hrest⟩ := hz
      subst sc
      obtain ⟨i, _, rfl⟩ := hrest
      exact hr.gen_sound pk_sk.1 pk_sk.2 hgen
    · simp only [cmaReal, cmaRealSourceFull, StateT.run_mk, support_bind, Set.mem_iUnion,
        support_pure, Set.mem_singleton_iff, exists_prop] at hz
      obtain ⟨sc, hsc, hrest⟩ := hz
      subst sc
      obtain ⟨i, _, rfl⟩ := hrest
      simpa [CmaData.Valid] using hpvalid
  · simp only [cmaReal, StateT.run_mk] at hz
    rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
        exists_prop] at hz
      obtain ⟨pk_sk, hgen, rfl⟩ := hz
      exact hr.gen_sound pk_sk.1 pk_sk.2 hgen
    · simp only [support_pure, Set.mem_singleton_iff] at hz
      subst z
      simpa [CmaData.Valid] using hpvalid

/-- The real CMA handler preserves keypair validity while bad is false. -/
theorem cmaReal_preserves_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) :
    (cmaReal M Commit Chal σ hr).PreservesNoBadInvariant
      (CmaData.Valid (rel := rel)) := by
  intro t p _ hpvalid z hz
  exact cmaReal_valid_preserved M Commit Chal σ hr t p hpvalid z hz

/-- Build the native H3 step facts from the two non-structural per-query facts. -/
theorem cmaH3StepFacts_of_stepTv_stepEq
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (h_step_tv_costly :
      ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
        cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t →
        ∀ (s : CmaData M Commit Chal Stmt Wit),
          CmaData.Valid (rel := rel) s →
            ENNReal.ofReal (tvDist
              (((cmaReal M Commit Chal σ hr) t).run (s, false))
              (((cmaSim M Commit Chal hr simT) t).run (s, false)))
              ≤ cmaSignEpsCore M Commit Chal ζ_zk β s)
    (h_step_eq_free :
      ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
        ¬ cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt) t →
        ∀ (p : CmaState M Commit Chal Stmt Wit),
          ((cmaReal M Commit Chal σ hr) t).run p =
            ((cmaSim M Commit Chal hr simT) t).run p) :
    CmaH3StepFacts M Commit Chal σ hr simT ζ_zk β where
  preservesValid := cmaReal_preserves_valid M Commit Chal σ hr
  stepTvCostly := h_step_tv_costly
  stepEqFree := h_step_eq_free
  badMono := cmaReal_bad_mono M Commit Chal σ hr

/-- Build the native H3 run facts from the query bound and expected-loss bound. -/
theorem cmaH3RunFacts_of_queryBound_expectedLoss
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞)
    (h_queryBound : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_expectedLoss :
      cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤ εBound) :
    CmaH3RunFacts M Commit Chal σ hr ζ_zk β A qS εBound where
  queryBound := h_queryBound
  badZero := cmaReal_probEvent_bad_eq_zero M Commit Chal σ hr A
  expectedLossLe := h_expectedLoss

/-! ## Native H3 factoring theorem -/

/-- Native H3 bridge with caller-supplied expected-cost bound.

This is the direct `QueryImpl.Stateful` replacement for the old H3
identical-until-bad instantiation. The hypotheses are factored into per-query
step facts and computation-specific run facts; no heap package or state
projection appears in the statement. -/
theorem cmaReal_cmaSim_advantage_le_H3_bound_of_expectedQuerySlack
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞)
    (stepFacts : CmaH3StepFacts M Commit Chal σ hr simT ζ_zk β)
    (runFacts : CmaH3RunFacts M Commit Chal σ hr ζ_zk β A qS εBound) :
    ENNReal.ofReal (cmaH3Advantage M Commit Chal σ hr simT A) ≤ εBound := by
  have h_bridge :=
    QueryImpl.Stateful.advantage_le_expectedQuerySlack_plus_probEvent_bad_of_inv_preserved
      (h₀ := cmaReal M Commit Chal σ hr)
      (h₁ := cmaSim M Commit Chal hr simT)
      (s_init := cmaDataInit M Commit Chal Stmt Wit)
      (Inv := CmaData.Valid (rel := rel))
      (chargedQuery := cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt))
      (querySlack := cmaSignEpsCore M Commit Chal ζ_zk β)
      (h_init_inv := cmaDataInit_valid M Commit Chal)
      stepFacts.preservesValid stepFacts.stepTvCostly stepFacts.stepEqFree
      stepFacts.badMono A runFacts.queryBound
  calc
    ENNReal.ofReal (cmaH3Advantage M Commit Chal σ hr simT A)
        = ENNReal.ofReal
            ((cmaReal M Commit Chal σ hr).advantage
              (cmaDataInit M Commit Chal Stmt Wit, false)
              (cmaSim M Commit Chal hr simT)
              (cmaDataInit M Commit Chal Stmt Wit, false) A) := by
            simp
    _ ≤ expectedQuerySlack (cmaReal M Commit Chal σ hr)
          (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt))
          (cmaSignEpsCore M Commit Chal ζ_zk β) A qS
          (cmaDataInit M Commit Chal Stmt Wit, false)
        + Pr[ fun z : Bool × CmaState M Commit Chal Stmt Wit => z.2.2 = true |
            (simulateQ (cmaReal M Commit Chal σ hr) A).run
              (cmaDataInit M Commit Chal Stmt Wit, false)] := h_bridge
    _ = cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS := by
            simp [runFacts.badZero, cmaH3ExpectedLoss]
    _ ≤ εBound := runFacts.expectedLossLe

end FiatShamir.Stateful
