/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
import VCVio.Interaction.UC.OpenTheory

/-!
# Raw syntax trees for open composition

This module defines the raw (un-quotiented) syntax trees for open-system
expressions, together with a structural interpretation function into any
target `OpenTheory`.

The inductive `Raw Atom Δ` has one constructor for each `OpenTheory` operation.
It is pattern-matchable and suitable for inspection, transformation, and
visualization, but it does not satisfy the `OpenTheory` equations: for example,
`Raw.map (Hom.id Δ) e` is a fresh `.map` node, not definitionally equal to `e`.

The quotient of `Raw` by the `OpenTheory` equations is defined in
`OpenSyntax.Expr`. The tagless-final (Church-encoded) companion is defined in
`OpenSyntax.Interp`.

## Main definitions

* `Raw`: inductive syntax tree for open-system expressions.
* `Raw.interpret`: structural recursion into any target `OpenTheory`.
* `Raw.Equiv`: the smallest equivalence relation containing the `OpenTheory`
  equations and closed under all constructors.
* `Raw.setoid`: packages `Raw.Equiv` as a `Setoid`.
-/

universe u

namespace Interaction
namespace UC
namespace OpenSyntax

/--
`Raw Atom Δ` is the raw syntax tree for open-system expressions of boundary `Δ`
generated by primitive atoms `Atom`.

Each constructor corresponds to one `OpenTheory` operation: `atom` injects
primitives, `map` adapts boundaries, `par` places systems side by side, `wire`
connects a shared boundary, and `plug` fully closes a system.

This type is not quotiented, so syntactically distinct trees are distinct
values even when they would evaluate the same way in any lawful `OpenTheory`.
See `Expr` for the quotiented version.
-/
inductive Raw (Atom : PortBoundary → Type u) : PortBoundary → Type (u + 1) where
  /-- Inject a primitive open component. -/
  | atom {Δ : PortBoundary} : Atom Δ → Raw Atom Δ
  /-- Adapt the exposed boundary along a structural morphism. -/
  | map {Δ₁ Δ₂ : PortBoundary} :
      PortBoundary.Hom Δ₁ Δ₂ → Raw Atom Δ₁ → Raw Atom Δ₂
  /-- Place two open systems side by side. -/
  | par {Δ₁ Δ₂ : PortBoundary} :
      Raw Atom Δ₁ → Raw Atom Δ₂ → Raw Atom (PortBoundary.tensor Δ₁ Δ₂)
  /-- Connect one shared boundary between two open systems. -/
  | wire {Δ₁ Γ Δ₂ : PortBoundary} :
      Raw Atom (PortBoundary.tensor Δ₁ Γ) →
      Raw Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂) →
      Raw Atom (PortBoundary.tensor Δ₁ Δ₂)
  /-- Close an open system against a matching context. -/
  | plug {Δ : PortBoundary} :
      Raw Atom Δ → Raw Atom (PortBoundary.swap Δ) → Raw Atom PortBoundary.empty
  /-- The monoidal unit (closed system with no boundary). -/
  | unit : Raw Atom PortBoundary.empty
  /-- The identity wire (coevaluation) on boundary `Γ`. -/
  | idWire (Γ : PortBoundary) :
      Raw Atom (PortBoundary.tensor (PortBoundary.swap Γ) Γ)

namespace Raw

/--
Interpret a raw expression in an arbitrary target open theory.

This is structural recursion: each constructor maps to the corresponding
`OpenTheory` operation. The target theory need not be lawful; lawfulness is
only required when reasoning about equivalence of interpretations.
-/
def interpret
    {Atom : PortBoundary → Type u}
    {Δ : PortBoundary}
    (e : Raw Atom Δ)
    (T : OpenTheory)
    (interp : ∀ {Δ : PortBoundary}, Atom Δ → T.Obj Δ)
    (unitVal : T.Obj PortBoundary.empty)
    (idWireVal : ∀ (Γ : PortBoundary),
      T.Obj (PortBoundary.tensor (PortBoundary.swap Γ) Γ)) :
    T.Obj Δ :=
  match e with
  | .atom a => interp a
  | .map f e => T.map f (e.interpret T interp unitVal idWireVal)
  | .par e₁ e₂ =>
    T.par (e₁.interpret T interp unitVal idWireVal)
      (e₂.interpret T interp unitVal idWireVal)
  | .wire e₁ e₂ =>
    T.wire (e₁.interpret T interp unitVal idWireVal)
      (e₂.interpret T interp unitVal idWireVal)
  | .plug e k =>
    T.plug (e.interpret T interp unitVal idWireVal)
      (k.interpret T interp unitVal idWireVal)
  | .unit => unitVal
  | .idWire Γ => idWireVal Γ

variable {Atom : PortBoundary → Type u} {T : OpenTheory}
    {interp : ∀ {Δ : PortBoundary}, Atom Δ → T.Obj Δ}
    {unitVal : T.Obj PortBoundary.empty}
    {idWireVal : ∀ (Γ : PortBoundary),
      T.Obj (PortBoundary.tensor (PortBoundary.swap Γ) Γ)}

@[simp]
theorem interpret_atom
    {Δ : PortBoundary}
    (a : Atom Δ) :
    (Raw.atom a).interpret T interp unitVal idWireVal = interp a :=
  rfl

@[simp]
theorem interpret_map
    {Δ₁ Δ₂ : PortBoundary}
    (f : PortBoundary.Hom Δ₁ Δ₂)
    (e : Raw Atom Δ₁) :
    (Raw.map f e).interpret T interp unitVal idWireVal =
      T.map f (e.interpret T interp unitVal idWireVal) :=
  rfl

@[simp]
theorem interpret_par
    {Δ₁ Δ₂ : PortBoundary}
    (e₁ : Raw Atom Δ₁)
    (e₂ : Raw Atom Δ₂) :
    (Raw.par e₁ e₂).interpret T interp unitVal idWireVal =
      T.par (e₁.interpret T interp unitVal idWireVal)
        (e₂.interpret T interp unitVal idWireVal) :=
  rfl

@[simp]
theorem interpret_wire
    {Δ₁ Γ Δ₂ : PortBoundary}
    (e₁ : Raw Atom (PortBoundary.tensor Δ₁ Γ))
    (e₂ : Raw Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂)) :
    (Raw.wire e₁ e₂).interpret T interp unitVal idWireVal =
      T.wire (e₁.interpret T interp unitVal idWireVal)
        (e₂.interpret T interp unitVal idWireVal) :=
  rfl

@[simp]
theorem interpret_plug
    {Δ : PortBoundary}
    (e : Raw Atom Δ)
    (k : Raw Atom (PortBoundary.swap Δ)) :
    (Raw.plug e k).interpret T interp unitVal idWireVal =
      T.plug (e.interpret T interp unitVal idWireVal)
        (k.interpret T interp unitVal idWireVal) :=
  rfl

@[simp]
theorem interpret_unit :
    (Raw.unit : Raw Atom PortBoundary.empty).interpret T interp unitVal idWireVal =
      unitVal :=
  rfl

@[simp]
theorem interpret_idWire
    (Γ : PortBoundary) :
    (Raw.idWire Γ : Raw Atom _).interpret T interp unitVal idWireVal =
      idWireVal Γ :=
  rfl

/--
`Raw.Equiv e₁ e₂` is the smallest equivalence relation on raw expressions at
the same boundary that contains the `OpenTheory` equations and is closed under
all constructors.

The equation constructors correspond to the four naturality/functoriality
laws of `OpenTheory.IsLawful`. The congruence constructors ensure that
equivalent sub-expressions can be substituted anywhere in a larger tree.
-/
inductive Equiv {Atom : PortBoundary → Type u} :
    {Δ : PortBoundary} → Raw Atom Δ → Raw Atom Δ → Prop where
  | refl {Δ : PortBoundary} {e : Raw Atom Δ} : Equiv e e
  | symm {Δ : PortBoundary} {e₁ e₂ : Raw Atom Δ} :
      Equiv e₁ e₂ → Equiv e₂ e₁
  | trans {Δ : PortBoundary} {e₁ e₂ e₃ : Raw Atom Δ} :
      Equiv e₁ e₂ → Equiv e₂ e₃ → Equiv e₁ e₃
  | map_id {Δ : PortBoundary} {e : Raw Atom Δ} :
      Equiv (.map (PortBoundary.Hom.id Δ) e) e
  | map_comp {Δ₁ Δ₂ Δ₃ : PortBoundary}
      {g : PortBoundary.Hom Δ₂ Δ₃}
      {f : PortBoundary.Hom Δ₁ Δ₂}
      {e : Raw Atom Δ₁} :
      Equiv (.map (PortBoundary.Hom.comp g f) e) (.map g (.map f e))
  | map_par {Δ₁ Δ₁' Δ₂ Δ₂' : PortBoundary}
      {f₁ : PortBoundary.Hom Δ₁ Δ₁'}
      {f₂ : PortBoundary.Hom Δ₂ Δ₂'}
      {e₁ : Raw Atom Δ₁}
      {e₂ : Raw Atom Δ₂} :
      Equiv
        (.map (PortBoundary.Hom.tensor f₁ f₂) (.par e₁ e₂))
        (.par (.map f₁ e₁) (.map f₂ e₂))
  | map_wire {Δ₁ Δ₁' Γ Δ₂ Δ₂' : PortBoundary}
      {f₁ : PortBoundary.Hom Δ₁ Δ₁'}
      {f₂ : PortBoundary.Hom Δ₂ Δ₂'}
      {e₁ : Raw Atom (PortBoundary.tensor Δ₁ Γ)}
      {e₂ : Raw Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂)} :
      Equiv
        (.map (PortBoundary.Hom.tensor f₁ f₂) (.wire e₁ e₂))
        (.wire
          (.map (PortBoundary.Hom.tensor f₁ (PortBoundary.Hom.id Γ)) e₁)
          (.map
            (PortBoundary.Hom.tensor
              (PortBoundary.Hom.id (PortBoundary.swap Γ))
              f₂)
            e₂))
  | map_plug {Δ₁ Δ₂ : PortBoundary}
      {f : PortBoundary.Hom Δ₁ Δ₂}
      {e : Raw Atom Δ₁}
      {k : Raw Atom (PortBoundary.swap Δ₂)} :
      Equiv
        (.plug (.map f e) k)
        (.plug e (.map (PortBoundary.Hom.swap f) k))
  | par_assoc {Δ₁ Δ₂ Δ₃ : PortBoundary}
      {e₁ : Raw Atom Δ₁}
      {e₂ : Raw Atom Δ₂}
      {e₃ : Raw Atom Δ₃} :
      Equiv
        (.map (PortBoundary.Equiv.tensorAssoc Δ₁ Δ₂ Δ₃).toHom
          (.par (.par e₁ e₂) e₃))
        (.par e₁ (.par e₂ e₃))
  | par_comm {Δ₁ Δ₂ : PortBoundary}
      {e₁ : Raw Atom Δ₁}
      {e₂ : Raw Atom Δ₂} :
      Equiv
        (.map (PortBoundary.Equiv.tensorComm Δ₁ Δ₂).toHom
          (.par e₁ e₂))
        (.par e₂ e₁)
  | par_leftUnit {Δ : PortBoundary}
      {e : Raw Atom Δ} :
      Equiv
        (.map (PortBoundary.Equiv.tensorEmptyLeft Δ).toHom
          (.par .unit e))
        e
  | par_rightUnit {Δ : PortBoundary}
      {e : Raw Atom Δ} :
      Equiv
        (.map (PortBoundary.Equiv.tensorEmptyRight Δ).toHom
          (.par e .unit))
        e
  | plug_eq_wire {Δ : PortBoundary}
      {e : Raw Atom Δ}
      {k : Raw Atom (PortBoundary.swap Δ)} :
      Equiv
        (.plug e k)
        (.map (PortBoundary.Equiv.tensorEmptyLeft PortBoundary.empty).toHom
          (.wire
            (.map (PortBoundary.Equiv.tensorEmptyLeft Δ).symm.toHom e)
            (.map (PortBoundary.Equiv.tensorEmptyRight
              (PortBoundary.swap Δ)).symm.toHom k)))
  | wire_idWire {Γ Δ₂ : PortBoundary}
      {e₂ : Raw Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂)} :
      Equiv
        (.wire (.idWire Γ) e₂)
        e₂
  | congr_map {Δ₁ Δ₂ : PortBoundary}
      {f : PortBoundary.Hom Δ₁ Δ₂}
      {e₁ e₂ : Raw Atom Δ₁} :
      Equiv e₁ e₂ → Equiv (.map f e₁) (.map f e₂)
  | congr_par {Δ₁ Δ₂ : PortBoundary}
      {e₁ e₁' : Raw Atom Δ₁}
      {e₂ e₂' : Raw Atom Δ₂} :
      Equiv e₁ e₁' → Equiv e₂ e₂' →
      Equiv (.par e₁ e₂) (.par e₁' e₂')
  | congr_wire {Δ₁ Γ Δ₂ : PortBoundary}
      {e₁ e₁' : Raw Atom (PortBoundary.tensor Δ₁ Γ)}
      {e₂ e₂' : Raw Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂)} :
      Equiv e₁ e₁' → Equiv e₂ e₂' →
      Equiv (.wire e₁ e₂) (.wire e₁' e₂')
  | congr_plug {Δ : PortBoundary}
      {e e' : Raw Atom Δ}
      {k k' : Raw Atom (PortBoundary.swap Δ)} :
      Equiv e e' → Equiv k k' →
      Equiv (.plug e k) (.plug e' k')

/--
Equivalent raw expressions interpret the same way in any lawful `OpenTheory`.
-/
theorem Equiv.interpret_eq
    {Atom : PortBoundary → Type u}
    {Δ : PortBoundary}
    {e₁ e₂ : Raw Atom Δ}
    (h : Equiv e₁ e₂)
    (T : OpenTheory)
    [OpenTheory.IsCompactClosed T]
    (interp : ∀ {Δ : PortBoundary}, Atom Δ → T.Obj Δ) :
    e₁.interpret T interp OpenTheory.IsMonoidal.unit OpenTheory.IsCompactClosed.idWire =
      e₂.interpret T interp OpenTheory.IsMonoidal.unit OpenTheory.IsCompactClosed.idWire := by
  induction h with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | map_id => simp [interpret]
  | map_comp => simp [interpret, OpenTheory.map_comp]
  | map_par => simp [interpret, OpenTheory.map_par]
  | map_wire => simp [interpret, OpenTheory.map_wire]
  | map_plug => simp [interpret, OpenTheory.map_plug]
  | par_assoc => simp [interpret, OpenTheory.par_assoc]
  | par_comm => simp [interpret, OpenTheory.par_comm]
  | par_leftUnit => simp [interpret, OpenTheory.par_leftUnit]
  | par_rightUnit => simp [interpret, OpenTheory.par_rightUnit]
  | plug_eq_wire => simp [interpret, OpenTheory.plug_eq_wire]
  | wire_idWire => simp [interpret, OpenTheory.wire_idWire]
  | congr_map _ ih => simp only [interpret_map]; rw [ih]
  | congr_par _ _ ih₁ ih₂ => simp only [interpret_par]; rw [ih₁, ih₂]
  | congr_wire _ _ ih₁ ih₂ => simp only [interpret_wire]; rw [ih₁, ih₂]
  | congr_plug _ _ ih₁ ih₂ => simp only [interpret_plug]; rw [ih₁, ih₂]

/--
The `Setoid` on `Raw Atom Δ` induced by `Raw.Equiv`.
-/
instance setoid (Atom : PortBoundary → Type u) (Δ : PortBoundary) :
    Setoid (Raw Atom Δ) where
  r := Equiv
  iseqv := ⟨fun _ => .refl, fun h => .symm h, fun h₁ h₂ => .trans h₁ h₂⟩

end Raw

end OpenSyntax
end UC
end Interaction
