-- Umbrella import for the `LatticeCryptoTest` library. The per-scheme
-- `Main.lean` files (Falcon/MLDSA/MLKEM) each define a top-level
-- `def main : IO Unit` for their executable target (`falcon_test`, `mldsa_test`,
-- `mlkem_test`) and are intentionally NOT imported here: importing more than
-- one of them in the same module triggers `main.match_NN` collisions from
-- Lean's pattern-match elaboration. Build them individually via
-- `lake build LatticeCryptoTest.Falcon.Main` (etc.) or via the exec targets.
-- Not regenerated by `scripts/update-lib.sh`.
import LatticeCryptoTest.Falcon.Helpers
import LatticeCryptoTest.Falcon.TestVectors
import LatticeCryptoTest.MLDSA.ACVPVectors
import LatticeCryptoTest.MLDSA.Helpers
import LatticeCryptoTest.MLKEM.ACVPVectors
import LatticeCryptoTest.MLKEM.Helpers
