/-
Copyright (c) 2026 Anonymized for double-blind review.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anonymized for double-blind review
-/
module

public import ToMathlib.ITree.Bisim.Defs

/-! # Equivalence laws for ITree (weak) bisimulation

Reflexivity, symmetry, and transitivity of `ITree.WeakBisim`, plus the
`Setoid (ITree F α)` instance generated by it.

## Strategy

The proofs use the Tarski greatest fixed point characterization
`WeakBisim t s = ∃ R, (closure under WeakBisimF) ∧ R t s`.

* **Reflexivity**: take `R := Eq`. The closure is immediate from the
  three head cases of `Match`.

* **Symmetry**: take `R := swap WeakBisim`. The closure follows from
  `Match.swap`.

* **Transitivity**: this is the deep one. Following the Coq
  `InteractionTrees` proof of `eutt_trans` (Xia et al., POPL 2020), the
  argument must reconcile the interaction between τ-stripping and head
  alignment when the intermediate term has a divergent step. We discharge
  it here without the paco "up-to" machinery by combining two workhorse
  devices:

  - the τ-absorption lemmas (`absorb_tauSteps_left`, `step_absorb_right`,
    `absorb_tauSteps_right`, `tauSteps_weakBisim_left`,
    `weakBisim_of_tauSteps_right`), which let us slide finite τ-strips
    through a `WeakBisim`, and
  - `Match.advance_left` / `Match.advance_right`, which advance a
    `Match WeakBisim` witness across a τ-strip on either endpoint.

  Together with `TauSteps.linear` they reduce the transitivity witness
  to a head-aligned `Match.trans_aligned`.

## Helpers

The τ-absorption lemmas are independently useful and are exported for
downstream proofs. They correspond to the "tau-eutt" lemmas in the
Coq library and are the workhorses of weak-bisim reasoning in the
absence of full transitivity.
-/

@[expose] public section

universe u

namespace ITree

variable {F : PFunctor.{u, u}} {α : Type u}

/-! ### `Bisim` is an equivalence -/

theorem Bisim.equivalence : Equivalence (Bisim (F := F) (α := α)) :=
  ⟨Bisim.refl', Bisim.symm', Bisim.trans'⟩

/-! ### Helper lemmas on `TauSteps` -/

namespace TauSteps

/-- If `t` has a pure head, then `TauSteps t t'` forces `t' = t`. -/
theorem rigid_of_pure {t t' : ITree F α} (r : α)
    (ht : shape' t = ⟨.pure r, PEmpty.elim⟩)
    (h : TauSteps t t') : t' = t := by
  cases h with
  | refl _ => rfl
  | step c hstep _ => exfalso; rw [ht] at hstep; cases hstep

/-- If `t` has a query head, then `TauSteps t t'` forces `t' = t`. -/
theorem rigid_of_query {t t' : ITree F α} (a : F.A) (c : F.B a → ITree F α)
    (ht : shape' t = ⟨.query a, c⟩)
    (h : TauSteps t t') : t' = t := by
  cases h with
  | refl _ => rfl
  | step c' hstep _ => exfalso; rw [ht] at hstep; cases hstep

/-- Determinism of τ-stripping on a step-headed tree: a stripping from
a step-headed tree either does nothing or proceeds through the unique
step continuation. -/
theorem step_cases {t t' : ITree F α} (c : PUnit.{u + 1} → ITree F α)
    (ht : shape' t = ⟨.step, c⟩) (h : TauSteps t t') :
    t' = t ∨ TauSteps (c PUnit.unit) t' := by
  cases h with
  | refl _ => exact Or.inl rfl
  | @step _ t'' c' ht' hr =>
      have hcc : c = c' := TauSteps.cont_eq ht ht'
      subst hcc
      exact Or.inr hr

end TauSteps

/-! ### `WeakBisim` is an equivalence -/

namespace WeakBisim

/-- Reflexivity: every tree is weakly bisimilar to itself. -/
@[refl] theorem refl (t : ITree F α) : t ≈ t := by
  refine coinduct Eq ?_ rfl
  rintro a b rfl
  rcases hsh : shape' a with ⟨sh, c⟩
  refine ⟨a, a, .refl _, .refl _, ?_⟩
  cases sh with
  | pure r =>
      refine Match.pure r ?_ ?_
      · rw [hsh]; congr 1; funext z; exact z.elim
      · rw [hsh]; congr 1; funext z; exact z.elim
  | step => exact Match.tau c c hsh hsh rfl
  | query a => exact Match.query a c c hsh hsh (fun _ => rfl)

/-- Symmetry: weak bisimilarity is symmetric. -/
@[symm] theorem symm {t s : ITree F α} (h : t ≈ s) : s ≈ t := by
  obtain ⟨R, hcl, hR⟩ := h
  refine coinduct (fun a b => R b a) ?_ hR
  intro a b hab
  obtain ⟨b', a', hb, ha, hm⟩ := hcl _ _ hab
  exact ⟨a', b', ha, hb, hm.swap⟩

/-! ### τ-absorption lemmas

These are the "tau-eutt" lemmas: τ-stripping on either side of a weak
bisimulation produces another weak bisimulation. They are independently
useful and form the building blocks for transitivity.
-/

/-- Absorbing a LHS τ-strip into a weak bisimulation. -/
theorem absorb_tauSteps_left {t t' s : ITree F α}
    (h : TauSteps t t') (hw : t' ≈ s) : t ≈ s := by
  refine coinduct (fun x y => ∃ x', TauSteps x x' ∧ x' ≈ y) ?_ ⟨t', h, hw⟩
  rintro a b ⟨a', haa', hab⟩
  obtain ⟨a'', b', ha'a'', hbb', M⟩ := hab.dest
  refine ⟨a'', b', haa'.trans ha'a'', hbb', M.mono ?_⟩
  intro x y hxy
  exact ⟨x, .refl _, hxy⟩

/-- Absorbing a single step τ-strip on the RHS of a weak bisimulation:
given `t ≈ s` and `s` step-headed with continuation `c`, conclude
`t ≈ (c .unit)`. The proof unfolds the bisim once and case-analyzes on
the head of `(c .unit)`, in the worst case unfolding the inner
`WeakBisim (ct .unit) (cs .unit)` one more level to reach a head match. -/
theorem step_absorb_right {t s : ITree F α} (c : PUnit.{u + 1} → ITree F α)
    (h : t ≈ s) (hstep : shape' s = ⟨.step, c⟩) :
    t ≈ (c PUnit.unit) := by
  refine coinduct
    (fun x z => x ≈ z ∨
      ∃ (s' : ITree F α) (c' : PUnit.{u + 1} → ITree F α),
        x ≈ s' ∧ shape' s' = ⟨.step, c'⟩ ∧ z = (c' PUnit.unit))
    ?_ (Or.inr ⟨s, c, h, hstep, rfl⟩)
  intro a b hab
  rcases hab with hab | ⟨s', c', hab, hstep', hz⟩
  · obtain ⟨a', b', ha, hb, M⟩ := hab.dest
    exact ⟨a', b', ha, hb, M.mono (fun _ _ hxy => Or.inl hxy)⟩
  subst hz
  obtain ⟨a', s₁, ha, hs, M⟩ := hab.dest
  rcases TauSteps.step_cases c' hstep' hs with hs_eq | hs_strict
  · subst hs_eq
    cases M with
    | pure _ _ hs_bad => exfalso; rw [hstep'] at hs_bad; cases hs_bad
    | query _ _ _ _ hs_bad _ => exfalso; rw [hstep'] at hs_bad; cases hs_bad
    | tau ct cs ht_a hs_a hr_weak =>
        have hcc : cs = c' := TauSteps.cont_eq hs_a hstep'
        subst hcc
        rcases hshc : shape' (cs PUnit.unit) with ⟨sh_c, c_cc⟩
        cases sh_c with
        | pure r =>
            have hshc_rw : shape' (cs PUnit.unit) =
                ⟨Shape.pure r, PEmpty.elim⟩ := by
              rw [hshc]; congr 1; funext z; exact z.elim
            obtain ⟨X, Y, hX, hY, MxY⟩ := hr_weak.dest
            have hY_eq : Y = (cs PUnit.unit) :=
              TauSteps.rigid_of_pure r hshc_rw hY
            subst hY_eq
            cases MxY with
            | pure r' ht_X hs_Y =>
                have hEq1 : (⟨Shape.pure r', PEmpty.elim⟩ :
                    (Poly F α).Obj (ITree F α)) =
                  ⟨Shape.pure r, PEmpty.elim⟩ := hs_Y.symm.trans hshc_rw
                have hrr : r' = r := Shape.pure.inj (Sigma.mk.inj hEq1).1
                subst hrr
                refine ⟨X, cs PUnit.unit,
                    ha.trans ((TauSteps.one ct ht_a).trans hX), .refl _, ?_⟩
                exact Match.pure r' ht_X hshc_rw
            | query _ _ _ _ hs_Y _ =>
                exfalso; rw [hs_Y] at hshc_rw; cases hshc_rw
            | tau _ _ _ hs_Y _ =>
                exfalso; rw [hs_Y] at hshc_rw; cases hshc_rw
        | step =>
            have hshc_rw : shape' (cs PUnit.unit) = ⟨Shape.step, c_cc⟩ := hshc
            refine ⟨a', cs PUnit.unit, ha, .refl _, ?_⟩
            refine Match.tau ct c_cc ht_a hshc_rw ?_
            exact Or.inr ⟨cs PUnit.unit, c_cc, hr_weak, hshc_rw, rfl⟩
        | query qa =>
            have hshc_rw : shape' (cs PUnit.unit) =
                ⟨Shape.query qa, c_cc⟩ := hshc
            obtain ⟨X, Y, hX, hY, MxY⟩ := hr_weak.dest
            have hY_eq : Y = (cs PUnit.unit) :=
              TauSteps.rigid_of_query qa c_cc hshc_rw hY
            subst hY_eq
            cases MxY with
            | pure _ _ hs_Y =>
                exfalso; rw [hs_Y] at hshc_rw; cases hshc_rw
            | query qa' c_X c_Y ht_X hs_Y hcc_XY =>
                have hEq : (⟨Shape.query qa', c_Y⟩ :
                    (Poly F α).Obj (ITree F α)) =
                  ⟨Shape.query qa, c_cc⟩ := hs_Y.symm.trans hshc_rw
                have hqq : qa' = qa := Shape.query.inj (Sigma.mk.inj hEq).1
                subst hqq
                have hcc : c_Y = c_cc := eq_of_heq (Sigma.mk.inj hEq).2
                subst hcc
                refine ⟨X, cs PUnit.unit,
                    ha.trans ((TauSteps.one ct ht_a).trans hX), .refl _, ?_⟩
                refine Match.query qa' c_X c_Y ht_X hshc_rw ?_
                intro b
                exact Or.inl (hcc_XY b)
            | tau _ _ _ hs_Y _ =>
                exfalso; rw [hs_Y] at hshc_rw; cases hshc_rw
  · refine ⟨a', s₁, ha, hs_strict, ?_⟩
    exact M.mono (fun _ _ hxy => Or.inl hxy)

/-- Absorbing a sequence of τ-strips on the RHS of a weak bisimulation. -/
theorem absorb_tauSteps_right {t s s' : ITree F α}
    (h : t ≈ s) (hstrip : TauSteps s s') : t ≈ s' := by
  induction hstrip generalizing t with
  | refl _ => exact h
  | @step _ _ c ht hr ih => exact ih (step_absorb_right c h ht)

/-- A τ-strip on the LHS of a weak bisimulation yields a weak bisimulation
between the stripped tree and the RHS. Dual to `absorb_tauSteps_right`. -/
theorem tauSteps_weakBisim_left {t t' s : ITree F α}
    (h : t ≈ s) (hstrip : TauSteps t t') : t' ≈ s :=
  (absorb_tauSteps_right h.symm hstrip).symm

/-- "Un-stripping" on the RHS: if `t ≈ s'` and `s` reaches `s'` by
τ-stripping, then `t ≈ s`. Built directly via coinduction carrying a
residual strip obligation on the RHS. -/
theorem weakBisim_of_tauSteps_right {t s s' : ITree F α}
    (h : t ≈ s') (hstrip : TauSteps s s') : t ≈ s := by
  refine coinduct (fun x y => ∃ y', TauSteps y y' ∧ x ≈ y') ?_ ⟨s', hstrip, h⟩
  rintro a b ⟨b', hbb', hab'⟩
  obtain ⟨a', b'', ha, hb, M⟩ := hab'.dest
  exact ⟨a', b'', ha, hbb'.trans hb, M.mono (fun _ y hxy => ⟨y, .refl _, hxy⟩)⟩

/-- Every τ-strip witnesses a weak bisimulation between its endpoints. -/
theorem weakBisim_of_tauSteps {t t' : ITree F α} (h : TauSteps t t') : t ≈ t' := by
  induction h with
  | refl _ => exact WeakBisim.refl _
  | step c ht _ ih => exact absorb_tauSteps_left (TauSteps.one c ht) ih

end WeakBisim

/-! ### `Match` advance lemmas

Advance a `Match WeakBisim` witness through a τ-strip on one of its
endpoints, producing a new `Match WeakBisim` at advanced endpoints.
These are the core tools for closing the misaligned case of
`WeakBisim.trans` — a τ-strip on the inner middle endpoint is absorbed
into the weak-bisim witness by `absorb_tauSteps_right` /
`tauSteps_weakBisim_left`, then the weak-bisim is unfolded once to
produce a new `Match` witness. -/

/-- Advance a `Match WeakBisim` witness on its RIGHT endpoint through a
τ-strip. Given `Match W x z1` and `TauSteps z1 z2`, produce
`x'`, `z'` with `TauSteps x x'`, `TauSteps z2 z'`, and
`Match W x' z'`. -/
theorem Match.advance_right {x z1 z2 : ITree F α}
    (Ma : Match WeakBisim x z1) (hlin : TauSteps z1 z2) :
    ∃ x' z', TauSteps x x' ∧ TauSteps z2 z' ∧ Match WeakBisim x' z' := by
  induction hlin generalizing x with
  | refl t => exact ⟨x, t, .refl _, .refl _, Ma⟩
  | @step _ z2' c Hz1 hr _ =>
      cases Ma with
      | pure _ _ Hp => exfalso; rw [Hp] at Hz1; cases Hz1
      | query _ _ _ _ Hq _ => exfalso; rw [Hq] at Hz1; cases Hz1
      | tau ct cs Hx_a Hz1_s hBisim =>
          have hcc : cs = c := TauSteps.cont_eq Hz1_s Hz1
          subst hcc
          have hB2 : WeakBisim (ct PUnit.unit) z2' :=
            WeakBisim.absorb_tauSteps_right hBisim hr
          obtain ⟨X, Y, hX, hY, MXY⟩ := hB2.dest
          refine ⟨X, Y, ?_, hY, MXY⟩
          exact (TauSteps.one ct Hx_a).trans hX

/-- Advance a `Match WeakBisim` witness on its LEFT endpoint through a
τ-strip. Given `Match W c1 y` and `TauSteps c1 c2`, produce
`c'`, `y'` with `TauSteps c2 c'`, `TauSteps y y'`, and
`Match W c' y'`. -/
theorem Match.advance_left {c1 c2 y : ITree F α}
    (Mb : Match WeakBisim c1 y) (hlin : TauSteps c1 c2) :
    ∃ c' y', TauSteps c2 c' ∧ TauSteps y y' ∧ Match WeakBisim c' y' := by
  induction hlin generalizing y with
  | refl t => exact ⟨t, y, .refl _, .refl _, Mb⟩
  | @step _ c2' c Hc1 hr _ =>
      cases Mb with
      | pure _ Hp _ => exfalso; rw [Hp] at Hc1; cases Hc1
      | query _ _ _ Hq _ _ => exfalso; rw [Hq] at Hc1; cases Hc1
      | tau ct cs Hc1_s Hy_s hBisim =>
          have hcc : c = ct := TauSteps.cont_eq Hc1 Hc1_s
          subst hcc
          have hB2 : WeakBisim c2' (cs PUnit.unit) :=
            WeakBisim.tauSteps_weakBisim_left hBisim hr
          obtain ⟨X, Y, hX, hY, MXY⟩ := hB2.dest
          refine ⟨X, Y, hX, ?_, MXY⟩
          exact (TauSteps.one cs Hy_s).trans hY

/-- Aligned-case transitivity at the `Match` level. Given two `Match`
witnesses that share a common middle tree `c`, produce a `Match` witness
for the composite relation `fun x y => ∃ z, x ≈ z ∧ z ≈ y`. Direct case
analysis on both matches, using shape determinism. -/
theorem Match.trans_aligned {c a_1 b_1 : ITree F α}
    (Ma : Match WeakBisim a_1 c) (Mb : Match WeakBisim c b_1) :
    Match (fun x y : ITree F α => ∃ z, x ≈ z ∧ z ≈ y) a_1 b_1 := by
  cases Ma with
  | pure r Ha Hc =>
      cases Mb with
      | pure r' Hc' Hb =>
          have heq : (⟨.pure r, PEmpty.elim⟩ : (Poly F α).Obj _) =
              ⟨.pure r', PEmpty.elim⟩ := Hc.symm.trans Hc'
          have hrr : r = r' := Shape.pure.inj (Sigma.mk.inj heq).1
          subst hrr
          exact .pure r Ha Hb
      | query _ _ _ Hc' _ _ => exfalso; rw [Hc] at Hc'; cases Hc'
      | tau _ _ Hc' _ _ => exfalso; rw [Hc] at Hc'; cases Hc'
  | query q ca ca' Ha Hc h =>
      cases Mb with
      | pure _ Hc' _ => exfalso; rw [Hc] at Hc'; cases Hc'
      | query q' cc cb Hc' Hb h' =>
          have heq : (⟨.query q, ca'⟩ : (Poly F α).Obj _) =
              ⟨.query q', cc⟩ := Hc.symm.trans Hc'
          have hqq : q = q' := Shape.query.inj (Sigma.mk.inj heq).1
          subst hqq
          have hcc : ca' = cc := eq_of_heq (Sigma.mk.inj heq).2
          exact .query q ca cb Ha Hb (fun b => ⟨ca' b, h b, hcc.symm ▸ h' b⟩)
      | tau _ _ Hc' _ _ => exfalso; rw [Hc] at Hc'; cases Hc'
  | tau ct cs Ha Hc h =>
      cases Mb with
      | pure _ Hc' _ => exfalso; rw [Hc] at Hc'; cases Hc'
      | query _ _ _ Hc' _ _ => exfalso; rw [Hc] at Hc'; cases Hc'
      | tau cs' cb Hc' Hb h' =>
          have hss : cs' = cs := TauSteps.cont_eq Hc' Hc
          exact .tau ct cb Ha Hb ⟨cs PUnit.unit, h, hss ▸ h'⟩

namespace WeakBisim

/-- Transitivity of weak bisimilarity.

**Proof.** By coinduction with relation `R x y := ∃ z, x ≈ z ∧ z ≈ y`.
The closure step unfolds both weak bisims once to obtain
`Ma : Match W a' c₁` with `TauSteps c c₁` and `Mb : Match W c₂ b'` with
`TauSteps c c₂`. Linearity of τ-stripping (`TauSteps.linear`) gives
either `TauSteps c₁ c₂` or `TauSteps c₂ c₁`; WLOG we take the former.

`Match.advance_right` on `Ma` through `TauSteps c₁ c₂` produces
`Ma' : Match W a'' c'` with `TauSteps c₂ c'`. `Match.advance_left` on
`Mb` through `TauSteps c₂ c'` produces `Mb' : Match W c'' b''` with
`TauSteps c' c''`.

Case analysis on the head of `c'` via `Ma'`:
* `pure` / `query`: rigidity of `TauSteps c' c''` forces `c'' = c'`, so
  `Match.trans_aligned` glues `Ma'` and `Mb'`.
* `.tau ct cs`: case split on `TauSteps c' c''`. When refl, aligned,
  glue. Otherwise `hrest : TauSteps (cs .unit) c''`. Case on the head
  of `c''` via `Mb'`:
  * `pure r'`: `absorb_tauSteps_right h_a hrest` gives
    `(ct .unit) ≈ c''`. Unfolding pins `a''` to some pure-`r'` tree
    reachable by τ-strips, producing `Match.pure`.
  * `query q'`: symmetric to pure via a query-aligned unfold.
  * `.tau ct'' cs''`: both sides step-headed. Produce `Match.tau` at
    `(a'', b'')` with continuations `(ct .unit)` and `(cs'' .unit)`.
    The residual coinductive relation is witnessed by choosing the
    intermediate term `z := ct'' .unit`:
    - `(ct .unit) ≈ (ct'' .unit)` via
      `absorb_tauSteps_right h_a (hrest.trans (TauSteps.one ct'' Hc''))`;
    - `(ct'' .unit) ≈ (cs'' .unit)` directly from `h_b`. -/
@[trans] theorem trans {t s u : ITree F α}
    (h₁ : t ≈ s) (h₂ : s ≈ u) : t ≈ u := by
  refine coinduct (fun x y => ∃ z, x ≈ z ∧ z ≈ y) ?_ ⟨s, h₁, h₂⟩
  rintro a b ⟨c, hac, hcb⟩
  obtain ⟨a', c₁, ha, hc₁, Ma⟩ := hac.dest
  obtain ⟨c₂, b', hc₂, hb, Mb⟩ := hcb.dest
  cases TauSteps.linear hc₁ hc₂ with
  | inl hlin =>
      obtain ⟨a'', c', ha', hc', Ma'⟩ := Match.advance_right Ma hlin
      obtain ⟨c'', b'', hc'', hb'', Mb'⟩ := Match.advance_left Mb hc'
      cases Ma' with
      | pure r Ha'' Hc' =>
          have : c'' = c' := TauSteps.rigid_of_pure r Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha', hb.trans hb'',
            (Match.pure r Ha'' Hc').trans_aligned Mb'⟩
      | query q ca ca' Ha'' Hc' hq =>
          have : c'' = c' := TauSteps.rigid_of_query q ca' Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha', hb.trans hb'',
            (Match.query q ca ca' Ha'' Hc' hq).trans_aligned Mb'⟩
      | tau ct cs Ha'' Hc' h_a =>
          rcases TauSteps.step_cases cs Hc' hc'' with hc_eq | hrest
          · subst hc_eq
            exact ⟨a'', b'', ha.trans ha', hb.trans hb'',
              (Match.tau ct cs Ha'' Hc' h_a).trans_aligned Mb'⟩
          · cases Mb' with
            | pure r' Hc'' Hb'' =>
                have hRB : WeakBisim (ct PUnit.unit) c'' :=
                  absorb_tauSteps_right h_a hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hYc : Y = c'' := TauSteps.rigid_of_pure r' Hc'' hY
                subst hYc
                cases MXY with
                | pure r'' HX HY =>
                    have heq : (⟨Shape.pure r'', PEmpty.elim⟩ :
                        (Poly F α).Obj (ITree F α)) =
                        ⟨Shape.pure r', PEmpty.elim⟩ := HY.symm.trans Hc''
                    have hrr : r' = r'' := (Shape.pure.inj (Sigma.mk.inj heq).1).symm
                    refine ⟨X, b'',
                      ha.trans (ha'.trans ((TauSteps.one ct Ha'').trans hX)),
                      hb.trans hb'', ?_⟩
                    exact Match.pure r'' HX (hrr ▸ Hb'')
                | query _ _ _ _ HY _ => exfalso; rw [HY] at Hc''; cases Hc''
                | tau _ _ _ HY _ => exfalso; rw [HY] at Hc''; cases Hc''
            | query q_outer cq_outer cq'_outer Hc'' Hb'' hq =>
                have hRB : WeakBisim (ct PUnit.unit) c'' :=
                  absorb_tauSteps_right h_a hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hYc : Y = c'' := TauSteps.rigid_of_query q_outer cq_outer Hc'' hY
                subst hYc
                cases MXY with
                | pure _ _ HY => exfalso; rw [HY] at Hc''; cases Hc''
                | query q'' cq_a cq_b HX HY h_q =>
                    have heq : (⟨Shape.query q'', cq_b⟩ :
                        (Poly F α).Obj (ITree F α)) =
                        ⟨Shape.query q_outer, cq_outer⟩ := HY.symm.trans Hc''
                    have hqq : q'' = q_outer :=
                      Shape.query.inj (Sigma.mk.inj heq).1
                    subst hqq
                    have hcc : cq_b = cq_outer := eq_of_heq (Sigma.mk.inj heq).2
                    subst hcc
                    refine ⟨X, b'',
                      ha.trans (ha'.trans ((TauSteps.one ct Ha'').trans hX)),
                      hb.trans hb'', ?_⟩
                    refine Match.query q'' cq_a cq'_outer HX Hb'' ?_
                    intro b
                    exact ⟨cq_b b, h_q b, hq b⟩
                | tau _ _ _ HY _ => exfalso; rw [HY] at Hc''; cases Hc''
            | tau ct'' cs'' Hc'' Hb'' h_b =>
                refine ⟨a'', b'', ha.trans ha', hb.trans hb'', ?_⟩
                refine Match.tau ct cs'' Ha'' Hb'' ?_
                refine ⟨ct'' PUnit.unit, ?_, h_b⟩
                have hTau : TauSteps (cs PUnit.unit) (ct'' PUnit.unit) :=
                  hrest.trans (TauSteps.one ct'' Hc'')
                exact absorb_tauSteps_right h_a hTau
  | inr hlin =>
      obtain ⟨c', b'', hc', hb', Mb'⟩ := Match.advance_left Mb hlin
      obtain ⟨a'', c'', ha'', hc'', Ma'⟩ := Match.advance_right Ma hc'
      cases Mb' with
      | pure r Hc' Hb'' =>
          have : c'' = c' := TauSteps.rigid_of_pure r Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha'', hb.trans hb',
            Ma'.trans_aligned (Match.pure r Hc' Hb'')⟩
      | query q ca ca' Hc' Hb'' hq =>
          have : c'' = c' := TauSteps.rigid_of_query q ca Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha'', hb.trans hb',
            Ma'.trans_aligned (Match.query q ca ca' Hc' Hb'' hq)⟩
      | tau ct cs Hc' Hb'' h_b =>
          rcases TauSteps.step_cases ct Hc' hc'' with hc_eq | hrest
          · subst hc_eq
            exact ⟨a'', b'', ha.trans ha'', hb.trans hb',
              Ma'.trans_aligned (Match.tau ct cs Hc' Hb'' h_b)⟩
          · cases Ma' with
            | pure r' Ha'' Hc'' =>
                have hRB : WeakBisim c'' (cs PUnit.unit) :=
                  tauSteps_weakBisim_left h_b hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hXc : X = c'' := TauSteps.rigid_of_pure r' Hc'' hX
                subst hXc
                cases MXY with
                | pure r'' HX HY =>
                    have heq : (⟨Shape.pure r'', PEmpty.elim⟩ :
                        (Poly F α).Obj (ITree F α)) =
                        ⟨Shape.pure r', PEmpty.elim⟩ := HX.symm.trans Hc''
                    have hrr : r' = r'' := (Shape.pure.inj (Sigma.mk.inj heq).1).symm
                    refine ⟨a'', Y, ha.trans ha'',
                      hb.trans (hb'.trans ((TauSteps.one cs Hb'').trans hY)),
                      ?_⟩
                    exact Match.pure r'' (hrr ▸ Ha'') HY
                | query _ _ _ HX _ _ => exfalso; rw [HX] at Hc''; cases Hc''
                | tau _ _ HX _ _ => exfalso; rw [HX] at Hc''; cases Hc''
            | query q_a cq_outer cq'_outer Ha'' Hc'' hq =>
                have hRB : WeakBisim c'' (cs PUnit.unit) :=
                  tauSteps_weakBisim_left h_b hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hXc : X = c'' := TauSteps.rigid_of_query q_a cq'_outer Hc'' hX
                subst hXc
                cases MXY with
                | pure _ HX _ => exfalso; rw [HX] at Hc''; cases Hc''
                | query q'' cq_a cq_b HX HY h_q =>
                    have heq : (⟨Shape.query q'', cq_a⟩ :
                        (Poly F α).Obj (ITree F α)) =
                        ⟨Shape.query q_a, cq'_outer⟩ := HX.symm.trans Hc''
                    have hqq : q'' = q_a := Shape.query.inj (Sigma.mk.inj heq).1
                    subst hqq
                    have hcc : cq_a = cq'_outer := eq_of_heq (Sigma.mk.inj heq).2
                    subst hcc
                    refine ⟨a'', Y, ha.trans ha'',
                      hb.trans (hb'.trans ((TauSteps.one cs Hb'').trans hY)),
                      ?_⟩
                    refine Match.query q'' cq_outer cq_b Ha'' HY ?_
                    intro b
                    exact ⟨cq_a b, hq b, h_q b⟩
                | tau _ _ HX _ _ => exfalso; rw [HX] at Hc''; cases Hc''
            | tau ct'' cs'' Ha'' Hc'' h_a =>
                refine ⟨a'', b'', ha.trans ha'', hb.trans hb', ?_⟩
                refine Match.tau ct'' cs Ha'' Hb'' ?_
                refine ⟨cs'' PUnit.unit, h_a, ?_⟩
                have hTau : TauSteps (ct PUnit.unit) (cs'' PUnit.unit) :=
                  hrest.trans (TauSteps.one cs'' Hc'')
                exact tauSteps_weakBisim_left h_b hTau

theorem equivalence : Equivalence (WeakBisim (F := F) (α := α)) :=
  ⟨WeakBisim.refl, fun {_ _} => WeakBisim.symm, fun {_ _ _} => WeakBisim.trans⟩

end WeakBisim

/-! ### Setoid instance generated by `WeakBisim` -/

instance instSetoid : Setoid (ITree F α) where
  r := WeakBisim
  iseqv := WeakBisim.equivalence

/-! ### `Bisim` implies `WeakBisim` -/

theorem Bisim.toWeakBisim {t s : ITree F α} (h : t ≅ s) : WeakBisim t s := by
  cases h; exact WeakBisim.refl _

end ITree
