/-
Copyright (c) 2026 Quang Dao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ToMathlib.ITree.Bisim.Defs

/-! # Equivalence laws for ITree (weak) bisimulation

Reflexivity, symmetry, and transitivity of `ITree.WeakBisim`, plus the
`Setoid (ITree F α)` instance generated by it. These laws complete the
`Equivalence` API for the intended notion of ITree program equivalence.

Strong bisimulation (`ITree.Bisim`) is reducibly definitional equality, so
its `Equivalence` proof is `Eq.refl`/`Eq.symm`/`Eq.trans`; we still record
the `Setoid` instance for `Bisim` for symmetry with `WeakBisim`.

The proofs of the `WeakBisim` equivalence laws are coinductive and rely on
helpers that will live in this file once the bisimulation tooling stabilises.
For now we leave them as `sorry`-marked stubs so that downstream code can
type-check against the API.
-/

@[expose] public section

universe u

namespace ITree

variable {F : PFunctor.{u, u}} {α : Type u}

/-! ### `Bisim` is an equivalence -/

@[refl] theorem Bisim.refl (t : ITree F α) : t ≅ t := Eq.refl t

@[symm] theorem Bisim.symm {t s : ITree F α} (h : t ≅ s) : s ≅ t := Eq.symm h

@[trans] theorem Bisim.trans {t s u : ITree F α}
    (h₁ : t ≅ s) (h₂ : s ≅ u) : t ≅ u := Eq.trans h₁ h₂

theorem Bisim.equivalence : Equivalence (Bisim (F := F) (α := α)) :=
  ⟨Bisim.refl, Bisim.symm, Bisim.trans⟩

/-! ### `WeakBisim` is an equivalence

Reflexivity and symmetry are direct applications of `WeakBisim.coinduct`.
Transitivity requires an additional "diamond" argument and is left as
`sorry` for now. -/

/-- Auxiliary inductive relation: `StepClosed t s` iff `t` and `s` agree
modulo finitely many leading silent steps. Used to derive
`WeakBisim.refl`. -/
inductive WeakBisim.StepClosed : ITree F α → ITree F α → Prop where
  | refl (t : ITree F α) : StepClosed t t
  | tauL {t s : ITree F α} (h : StepClosed t s) : StepClosed (step t) s
  | tauR {t s : ITree F α} (h : StepClosed t s) : StepClosed t (step s)

private theorem WeakBisim.stepClosed_implies (t s : ITree F α)
    (h : StepClosed t s) : t ≈ s := by
  refine WeakBisim.coinduct StepClosed ?_ t s h
  rintro a b hab
  cases hab with
  | refl =>
      rcases hsh : shape' a with ⟨sh, c⟩
      cases sh with
      | pure r =>
          left
          refine ⟨r, ?_, ?_⟩
          · congr 1; funext z; exact z.elim
          · congr 1; funext z; exact z.elim
      | step =>
          right; right; left
          refine ⟨c PUnit.unit, ?_, ?_⟩
          · change ((⟨.step, c⟩ : (Poly F α).Obj _) : _) =
              ⟨.step, fun _ => c PUnit.unit⟩
            congr 1
          · have ha : a = step (c PUnit.unit) := by
              apply PFunctor.M.eq_of_dest_eq
              have hms : PFunctor.M.dest (step (c PUnit.unit) : ITree F α) =
                  ⟨.step, fun _ : PUnit => c PUnit.unit⟩ :=
                PFunctor.M.dest_mk _
              rw [hms]
              exact hsh.trans (by congr 1)
            rw [ha]; exact StepClosed.tauR (StepClosed.refl _)
      | query x =>
          right; left
          exact ⟨x, c, c, rfl, rfl, fun _ => StepClosed.refl _⟩
  | tauL h =>
      right; right; left
      exact ⟨_, shape'_step _, h⟩
  | tauR h =>
      right; right; right
      exact ⟨_, shape'_step _, h⟩

@[refl] theorem WeakBisim.refl (t : ITree F α) : t ≈ t :=
  stepClosed_implies t t (.refl t)

@[symm] theorem WeakBisim.symm {t s : ITree F α} (h : t ≈ s) : s ≈ t := by
  refine WeakBisim.coinduct (fun a b => WeakBisim b a) ?_ s t h
  rintro a b hab
  cases hab with
  | pure b a r hb ha => left; exact ⟨r, ha, hb⟩
  | query b a x c c' hb ha hcc => right; left; exact ⟨x, c', c, ha, hb, hcc⟩
  | tauL b a t' hb hbb => right; right; right; exact ⟨t', hb, hbb⟩
  | tauR b a s' hb hbb => right; right; left; exact ⟨s', hb, hbb⟩

@[trans] theorem WeakBisim.trans {t s u : ITree F α}
    (h₁ : t ≈ s) (h₂ : s ≈ u) : t ≈ u := by
  sorry

theorem WeakBisim.equivalence : Equivalence (WeakBisim (F := F) (α := α)) :=
  ⟨WeakBisim.refl, fun {_ _} => WeakBisim.symm, fun {_ _ _} => WeakBisim.trans⟩

/-! ### Setoid instance generated by `WeakBisim` -/

instance instSetoid : Setoid (ITree F α) where
  r := WeakBisim
  iseqv := WeakBisim.equivalence

/-! ### `Bisim` implies `WeakBisim` -/

theorem Bisim.toWeakBisim {t s : ITree F α} (h : t ≅ s) : WeakBisim t s := by
  cases h
  exact WeakBisim.refl _

end ITree
