/-
Copyright (c) 2026 Quang Dao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ToMathlib.ITree.Bisim.Defs

/-! # Equivalence laws for ITree (weak) bisimulation

Reflexivity, symmetry, and transitivity of `ITree.WeakBisim`, plus the
`Setoid (ITree F α)` instance generated by it. These laws complete the
`Equivalence` API for the intended notion of ITree program equivalence.

Strong bisimulation (`ITree.Bisim`) is reducibly definitional equality, so
its `Equivalence` proof is `Eq.refl`/`Eq.symm`/`Eq.trans`; we still record
the `Setoid` instance for `Bisim` for symmetry with `WeakBisim`.

The proofs of the `WeakBisim` equivalence laws are coinductive and rely on
helpers that will live in this file once the bisimulation tooling stabilises.
For now we leave them as `sorry`-marked stubs so that downstream code can
type-check against the API.
-/

@[expose] public section

universe u

namespace ITree

variable {F : PFunctor.{u, u}} {α : Type u}

/-! ### `Bisim` is an equivalence -/

@[refl] theorem Bisim.refl (t : ITree F α) : t ≅ t := Eq.refl t

@[symm] theorem Bisim.symm {t s : ITree F α} (h : t ≅ s) : s ≅ t := Eq.symm h

@[trans] theorem Bisim.trans {t s u : ITree F α}
    (h₁ : t ≅ s) (h₂ : s ≅ u) : t ≅ u := Eq.trans h₁ h₂

theorem Bisim.equivalence : Equivalence (Bisim (F := F) (α := α)) :=
  ⟨Bisim.refl, Bisim.symm, Bisim.trans⟩

/-! ### `WeakBisim` is an equivalence

The proofs are scaffolded with `sorry`. They will be discharged once the
project's coinductive proof tooling matures (typically via a parametric
`bisim_up_to`-style principle or via the `coinductive_predicate`-generated
greatest fixpoint API). -/

@[refl] theorem WeakBisim.refl (t : ITree F α) : t ≈ t := by
  sorry

@[symm] theorem WeakBisim.symm {t s : ITree F α} (h : t ≈ s) : s ≈ t := by
  sorry

@[trans] theorem WeakBisim.trans {t s u : ITree F α}
    (h₁ : t ≈ s) (h₂ : s ≈ u) : t ≈ u := by
  sorry

theorem WeakBisim.equivalence : Equivalence (WeakBisim (F := F) (α := α)) :=
  ⟨WeakBisim.refl, WeakBisim.symm, WeakBisim.trans⟩

/-! ### Setoid instance generated by `WeakBisim` -/

instance instSetoid : Setoid (ITree F α) where
  r := WeakBisim
  iseqv := WeakBisim.equivalence

/-! ### `Bisim` implies `WeakBisim` -/

theorem Bisim.toWeakBisim {t s : ITree F α} (h : t ≅ s) : WeakBisim t s := by
  cases h
  exact WeakBisim.refl _

end ITree
